### ISSUE TITLE
read_params_file: parameter not found:

### ISSUE THREAD

**Issue by segator** [Tentacule/PgsToSrt#2]
when executing 
dotnet D:\pgstosrt\PgsToSrt.dll --input "D:\23.sup" --output "D:\23.srt" --tesseractlanguage tha
 on a specific sup file I got
2019/12/07 17:49:26.754|INFO|Starting OCR for 8 items...
read_params_file: parameter not found:

yes I have the tha tesseractlanguage
you can find the sup file here
[23.zip](https://github.com/Tentacule/PgsToSrt/files/3935308/23.zip)

**Comment by Tentacule** [comment]
It's working on my side:

1
00:00:06,234 --> 00:00:07,319
คนสุดทำย

Can you give me the size of the "tha.traineddata" file ?

**Comment by Tentacule** [comment]
Seems like a tesseract trained.data v4 file is used instead of v3.04
