### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by serpafi** [Tentacule/PgsToSrt#20]
Bonjour,
J'ai bien utilisé votre création qui fonctionne très bien.
Je vous avoue l'avoir utilisé pour mon logiciel "TAO-MKV" mais je suis passé par un autre processus en tesseract 5.0.X LSTM.
Cependant même si votre programme ne soit pas rapide, il reste très efficace ET surtout léger (j'ai pu le réduire à 19Mo contre 250Mo pour l'officiel "sans les tessdata bien sur" ).
Je n'ai aucune idée de comment extraire les bmp sous-titres et les timestamps (sous forme texte) mais si vous souhaitez inclure votre savoir faire, rapidité et efficacité dans TAO-MKV, https://github.com/serpafi/TAO-MKV
on sera ravi de votre travail qui ne sera pas spoiler mais mis en avant (textes, liens ou autres seront publiés directement dans le logiciel).
Cordialement

**Comment by Tentacule** [comment]
Bonjour,

Pour améliorer la vitesse de traitement il faut extraire les sous-titres avec mkvextract et utiliser les .sup obtenus dans pgstostr au lieu des mkv directement.

Pour l'extraction des bmp et timestamps, c'est en grande partie le package libse qui s'en occupe (voir BluRaySupParser.ParseBluRaySup) et un peu [BluRaySupParserExtensions](https://github.com/Tentacule/PgsToSrt/blob/master/PgsToSrt/BluRaySup/BluRaySupParserExtensions.cs) pour obtenir le bitmap final.

**Comment by serpafi** [comment]
Bonjour,
Justement,TAO-mkv extrait le sup avant le traitement OCR.
J'ai finalement codé dans mon logiciel un extracteur de timestamps mais impossible de comprendre comment extraire les bmp :'D
Merci pour vos infos mais je n'arrive pas à comprendre votre code (je connais que batch et autoit) en tout cas, continuez comme ça. 
Bon travail.
