### ISSUE TITLE
How to Use with MKS?

### ISSUE THREAD

**Issue by RedSoxFan04** [Tentacule/PgsToSrt#21]
I see the examples for MKV and sup files, but I used MKVToolNix GUI to extract my subtitles, which gave me MKS files. Also, how can I have PgsToSrt convert all tracks in the MKS file?

**Comment by Tentacule** [comment]
I added mks support in version 1.4.1, it works the same way as mkv files.

You can convert all the tracks of the same language with --trackLanguage option.
It's not yet posssible to convert all tracks at once.
