### ISSUE TITLE
Problem with Ubuntu 23.04 and libtesseract4

### ISSUE THREAD

**Issue by Imantsg** [Tentacule/PgsToSrt#36]
I wanted to use PgsToSrt under Ubuntu 23.04 but it comes with libtesseract5 and I did not find what to install libtesseract4. Is it possible to make PgsToSrt use libtesseract5 instead of libtesseract4?

**Comment by Tentacule** [comment]
I added Tesseract 5 support in the latest release (add `--tesseractversion 5` in the command line)
