### ISSUE TITLE
Accept other leptonica's names

### ISSUE THREAD

**Issue by glu8716** [Tentacule/PgsToSrt#38]
On ArchLinux the required library `liblept.so` is actually called `libleptonica.so`. I had to make the following symlink in order to make PgsToSrt to read it: `ln -s /usr/lib/libleptonica.so.6 /usr/lib/liblept.so.5`. Would be good if the program could read the name `libleptonica.so` by itself.

**Comment by Tentacule** [comment]
I added new command line parameters to override leptonica's name/version in this [release](https://github.com/Tentacule/PgsToSrt/releases/tag/v1.4.4)

In your case adding this should work :
`--libleptname leptonica --libleptversion 6`
