### ISSUE TITLE
Model used for trained data

### ISSUE THREAD

**Issue by cmjordan42** [Tentacule/PgsToSrt#42]
It doesn't seem like the Tesseract trained data set is optional (i.e. 'fast' vs 'best') and as far as I can tell, you are using 'fast'. Is that the case?

There may also be corruption somewhere in the trained data you have (at least, for eng) as I just noticed totally nonsensical series of characters in the conversion of a single basic word when it is multi-line. Something like...

```
The brown fox jumps over the lazy
qj2]a%sLo1
```

**Comment by Tentacule** [comment]
In the docker image, trained data are downloaded from here: https://github.com/tesseract-ocr/tessdata/, from the readme it looks like a version between 'best' and 'fast'

If you want to try other data (ie. https://github.com/tesseract-ocr/tessdata_best), you'll have to download them and manually run PgsToSrt.

It'll be interesting if you could provide me a sample of the file you are using.

**Comment by GFoley83** [comment]
The `eng.traineddata` from `tessdata_best` should give you pretty much perfect results @cmjordan42.

See my comment here: https://github.com/Tentacule/PgsToSrt/issues/41#issuecomment-2058217759

**Comment by Tentacule** [comment]
this issue is fixed in the latest version
