### ISSUE TITLE
`docker` image bug and out of data README: `trackLanguage` -> `tracklanguage`

### ISSUE THREAD

**Issue by zwimer** [Tentacule/PgsToSrt#46]
The CLI option `trackLanguage` seems to now be `tracklanguage` according to `entrypoint.sh`. 

Attempting to use the `TRACK_LANGUAGE` environment variable with the currently existing docker image fails with the error that the argument `trackLanguage` is unknown. Replacing `/entrypoint.sh` with what is currently on master fixes this issue.

The README also still lists `trackLanguage` as an option rather than `tracklanguage`.

**Comment by Tentacule** [comment]
I updated readme and entrypoint.sh, thanks.
