### ISSUE TITLE
Update upstream dependencies, consider re-doing your customizations on top of the original code instead.

### ISSUE THREAD

**Issue by robertbaker** [Tentacule/PgsToSrt#9]
You changed the code-style of the original code which makes merging upstream changes a lot harder on yourself.
In one case, IMO `get => TimeSpan.Milliseconds;
` is more readable than what you changed it to:
```         
get
{
    return TimeSpan.Milliseconds;
}
```

You can refactor your modifications so you override functionality and thus you can use the upstream nuget package and make updates a lot easier for those dependencies. Git submodules can be utilized if you must have a clone of the code in your project.

**Comment by Tentacule** [comment]
External libse/tesseract projects have been replaced by their nuget packages.
